# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6816b3b692ae5c9be3dcc8044434d2f378ad193d4e6c25ad50610d84b1ae555b786e7f9d16bf7d56db8660bf725d12fe5fc924549118157e07e315f7c0d31250

test:
  secret_key_base: 12165c1da6b12442eea4be280480bc75991d1cbe0f7e67ef1068ff6550259d4e02299e2d3e5d219baf20a632e3cbdac4d40ee372dcf5fe4a05a9a7c3ae6e176d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
